---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      version: 1.17.*
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
  interval: 15m
  timeout: 10m
  releaseName: cert-manager
  valuesFrom:
  - kind: ConfigMap
    name: cert-manager-values
    valuesKey: values.yaml
