---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: onepassword
  namespace: onepassword
spec:
  chart:
    spec:
      chart: connect
      version: 1.17.*
      sourceRef:
        kind: HelmRepository
        name: onepassword
        namespace: flux-system
  interval: 30m
  timeout: 25m
  releaseName: onepassword
  valuesFrom:
  - kind: ConfigMap
    name: onepassword-values
    valuesKey: values.yaml
  - kind: Secret
    name: onepassword-secret-values
    valuesKey: notesPlain
