---
apiVersion: v1
kind: ConfigMap
metadata:
  name: onepassword-values
  namespace: onepassword
data:
  values.yaml: |-
    operator:
      create: true
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 128Mi
    connect:
      api:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 128Mi
      sync:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 128Mi
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          kubernetes.io/ingress.class: nginx-internal
          kubernetes.io/tls-acme: 'true'
        ingressClassName: "nginx-internal"
        pathType: Prefix
        hosts:
          - host: onepassword.drik.it
            paths: []
        extraPaths: []
        tls:
          - secretName: onepassword-tls
            hosts:
              - onepassword.drik.it
