---

installation_drive:
  name: /dev/nvme0n1
  efi_partition_suffix: p1
  efi_partition_label: efi
  root_partition_suffix: p2
  root_partition_label: arch

installation_kernel_version: linux-lts

installation_install_zfs_on_archiso: false
installation_zfs_lts_packages: zfs-dkms zfs-utils
installation_zfs_git_packages: zfs-dkms-git zfs-utils-git
installation_zfs_packages: "{{ installation_zfs_lts_packages if installation_kernel_version == 'linux-lts' else installation_zfs_git_packages }}"

installation_efi_partiton_mount_point: /efi
installation_uki_enabled: true
installation_secure_boot_enabled: true

installation_systemd_boot_enabled: true
installation_grub_enabled: false

installation_zfs_virt_zpool_properties: >
  -O recordsize=64KiB
installation_zfs_additional_zpool_properties: "{{ installation__zfs_virt_zpool_properties if gpu_manufacturer == 'virt' else '' }}"
installation_zfs_zpool_compression: lz4
installation_zfs_root_dataset: "{{ installation_drive.root_zpool }}/root"

installation_intel_packages: mesa vulkan-intel intel-media-driver intel-gpu-tools
installation_amd_packages: mesa vulkan-radeon
installation_nvidia_packages: nvidia-open-dkms nvidia-settings
installation_virt_packages: qemu-guest-agent
installation_additional_packages: >
  {{ installation_intel_packages if gpu_manufacturer == 'intel'
  else installation_amd_packages if gpu_manufacturer == 'amd'
  else installation_nvidia_packages if gpu_manufacturer == 'nvidia'
  else installation_virt_packages if gpu_manufacturer == 'virt'
  else '' }}

installation_intel_kernel_cmdline: nowatchdog
installation_amd_kernel_cmdline: nowatchdog split_lock_detect=off
installation_nvidia_kernel_cmdline: nvidia-drm.modeset=1 nowatchdog
installation_virt_kernel_cmdline:
installation_kernel_cmdline: >
  {{ installation_intel_kernel_cmdline if gpu_manufacturer == 'intel'
  else installation_amd_kernel_cmdline if gpu_manufacturer == 'amd'
  else installation_nvidia_kernel_cmdline if gpu_manufacturer == 'nvidia'
  else installation_virt_kernel_cmdline if gpu_manufacturer == 'virt'
  else '' }}

installation_intel_mkinicpio_modules: zfs i915
installation_amd_mkinicpio_modules: zfs amdgpu
installation_nvidia_mkinicpio_modules: zfs nvidia nvidia_modeset nvidia_uvm nvidia_drm
installation_virt_mkinicpio_modules: zfs virtio virtio_blk virtio_pci virtio_net virtio_ring
installation_mkinicpio_modules: >
  {{ installation_intel_mkinicpio_modules if gpu_manufacturer == 'intel'
  else installation_amd_mkinicpio_modules if gpu_manufacturer == 'amd'
  else installation_nvidia_mkinicpio_modules if gpu_manufacturer == 'nvidia'
  else installation_virt_mkinicpio_modules if gpu_manufacturer == 'virt'
  else '' }}

installation_mkinitcpio_hooks: "base udev autodetect microcode modconf kms keyboard keymap consolefont block zfs filesystems"

installation_existing_secureboot_keys: false
installation_reboot_after_install: true
