---

installation_drive:
  name: /dev/nvme0n1
  efi_partition_suffix: p1
  efi_partition_label: efi
  root_partition_suffix: p2
  root_zpool: arch
installation_kernel_version: linux

hostname: mm-b850
# nvidia, intel, virt
gpu_manufacturer: amd
# en_PL, pl_PL
system_lang: pl_PL

kvm_enabled: false
cli_enabled: false
ssh_client_enabled: false

crypt_passphrase: "{{ lookup('community.general.bitwarden', 'mm_secrets', field='crypt_passphrase') | join }}"
user_name: "{{ mm_user_name }}"
user_password: "{{ mm_user_password }}"
