---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ragflow-values
  namespace: ragflow
data:
  values.yaml: |-
    infinity:
      image:
        repository: infiniflow/infinity
        tag: v0.5.2
      storage:
        className:
        capacity: 5Gi

    elasticsearch:
      storage:
        className:
        capacity: 20Gi

    minio:
      storage:
        className:
        capacity: 5Gi

    mysql:
      storage:
        className:
        capacity: 5Gi

    redis:
      storage:
        className:
        capacity: 5Gi

    ingress:
      enabled: true
      className: "nginx-internal"
      annotations:
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        kubernetes.io/ingress.class: nginx-internal
      hosts:
        - host: ragflow.drik.it
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: ragflow-certs
          hosts:
            - ragflow.drik.it
