---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mumble
  namespace: mumble
spec:
  chart:
    spec:
      chart: mumble
      version: 0.1.*
      sourceRef:
        kind: HelmRepository
        name: drik-homelab
        namespace: flux-system
  interval: 30m
  timeout: 25m
  releaseName: mumble
  valuesFrom:
  - kind: ConfigMap
    name: mumble-values
    valuesKey: values.yaml
  - kind: Secret
    name: mumble-secret-values
    valuesKey: notesPlain