---

- name: Add required ENV variables
  ansible.builtin.blockinfile:
    path: /home/{{ user_name }}/.bash_profile
    insertbefore: EOF
    block: |
      # Modified by Ansible
      export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
      export SSH_ASKPASS='/usr/bin/ksshaskpass'

- name: Enable ssh-agent service
  ansible.builtin.systemd_service:
    name: ssh-agent
    state: started
    enabled: true
    scope: user
  become: true
  become_user: "{{ user_name }}"

- name: Create autostart directory
  ansible.builtin.file:
    path: /home/{{ user_name }}/.config/autostart
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0755"

- name: Add ssh-add to autostart
  ansible.builtin.copy:
    content: |
      [Desktop Entry]
      Exec=ssh-add -q ~/.ssh/{{ ssh_key_name }}
      Name=ssh-add
      Type=Application
    dest: /home/{{ user_name }}/.config/autostart/ssh-add.desktop
    mode: "0644"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Configure ssh config
  ansible.builtin.template:
    src: config.j2
    dest: /home/{{ user_name }}/.ssh/config
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0600"
