---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-values
  namespace: kube-system
data:
  values.yaml: |-
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        memory: 512Mi
