---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  chart:
    spec:
      chart: qbittorrent
      version: 0.1.*
      sourceRef:
        kind: HelmRepository
        name: drik-homelab
        namespace: flux-system
  interval: 30m
  timeout: 25m
  releaseName: qbittorrent
  valuesFrom:
  - kind: ConfigMap
    name: qbittorrent-values
    valuesKey: values.yaml
