---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-values
  namespace: qbittorrent
data:
  values.yaml: |-
    replicaCount: 1

    ingress:
      enabled: true
      className: "nginx-internal"
      annotations:
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        kubernetes.io/ingress.class: nginx-internal
      hosts:
        - host: qbit.drik.it
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: qbittorrent-certs
          hosts:
            - qbit.drik.it

    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 30Gi
      data:
        enabled: true
        storageClass: nfs-media
        accessMode: ReadWriteMany
        size: 41Ti

    resources:
      requests:
        cpu: 250m
        memory: 2Gi
      limits:
        memory: 2Gi
