---

- name: Ensure packages are installed
  community.general.pacman:
    name:
      - cups
      - cups-pdf
      - system-config-printer
      - ghostscript
      - gsfonts
      - foomatic-db-engine
      - foomatic-db
      - foomatic-db-nonfree
      - foomatic-db-nonfree-ppds
    state: present

- name: Ensure cups socket is enabled
  ansible.builtin.systemd:
    name: cups.socket
    enabled: true

- name: Set paper size
  ansible.builtin.copy:
    content: a4
    dest: /etc/papersize
    owner: root
    group: root
    mode: "0644"
