---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  chart:
    spec:
      chart: metrics-server
      version: 3.11.*
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
  interval: 30m
  timeout: 25m
  releaseName: metrics-server
  valuesFrom:
  - kind: ConfigMap
    name: metrics-server-values
    valuesKey: values.yaml
