---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-server-values
  namespace: metrics-server
data:
  values.yaml: |-
    replicas: 1
    args:
      - --kubelet-preferred-address-types=InternalIP
      - --kubelet-insecure-tls
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 256Mi
