---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zfs-localpv-values
  namespace: zfs-localpv
data:
  values.yaml: |-
    analytics:
      enabled: false
    zfsNode:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 128Mi
    zfsController:
      resources:
        requests:
          cpu: 250m
          memory: 256Mi
        limits:
          memory: 256Mi
