---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: zfs-localpv
  namespace: zfs-localpv
spec:
  chart:
    spec:
      chart: zfs-localpv
      version: 2.7.*
      sourceRef:
        kind: HelmRepository
        name: zfs-localpv
        namespace: flux-system
  interval: 30m
  timeout: 25m
  releaseName: zfs-localpv
  valuesFrom:
  - kind: ConfigMap
    name: zfs-localpv-values
    valuesKey: values.yaml
