---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-values
  namespace: ingress-nginx
data:
  values.yaml: |-
    controller:
      replicaCount: 1
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: 1
          memory: 1024Mi
      ingressClassResource:
        name: nginx
        default: true
      dnsConfig:
        options:
          - name: ndots
            value: '1'
      service:
        loadBalancerIP: 192.168.101.11
      allowSnippetAnnotations: true
