---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-internal-values
  namespace: ingress-nginx-internal
data:
  values.yaml: |-
    nameOverride: ingress-nginx-internal
    controller:
      replicaCount: 1
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: 1
          memory: 1024Mi
      ingressClassResource:
        name: nginx-internal
        controllerValue: "k8s.io/ingress-nginx-internal"
        default: false
      ingressClass: nginx-internal
      dnsConfig:
        options:
          - name: ndots
            value: '1'
      service:
        loadBalancerIP: 192.168.101.12
      allowSnippetAnnotations: true
