---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  chart:
    spec:
      chart: authentik
      version: 2025.8.*
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  interval: 30m
  timeout: 25m
  releaseName: authentik
  valuesFrom:
  - kind: ConfigMap
    name: authentik-values
    valuesKey: values.yaml
  - kind: Secret
    name: authentik-secret-values
    valuesKey: notesPlain
