---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range
  namespace: kube-system
spec:
  limits:
  - default:
      memory: 128Mi
    defaultRequest:
      memory: 128Mi
      cpu: 100m
    type: Container
