---

- name: Ensure zfs is installed
  community.general.pacman:
    name: "{{ zfs_packages }}"
    state: present

- name: Create required services and timers
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
    owner: root
    group: root
  loop:
    - src: zfs-trim@.timer
      dest: /etc/systemd/system/zfs-trim@.timer
    - src: zfs-trim@.service
      dest: /etc/systemd/system/zfs-trim@.service
    - src: zfs-load-key.service
      dest: /etc/systemd/system/zfs-load-key.service

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable required services and targets
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
  loop:
    - zfs-mount.service
    - zfs-import-cache.service
    - zfs.target
    - zfs-import.target
    - zfs-load-key.service

- name: Create zpools
  ansible.builtin.include_tasks: zpool.yml
  loop: "{{ zfs_zpools }}"
  loop_control:
    loop_var: zpool
