---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range
  namespace: ocis
spec:
  limits:
  - default:
      memory: 256Mi
    defaultRequest:
      memory: 256Mi
      cpu: 250m
    type: Container
