---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prowlarr-values
  namespace: prowlarr
data:
  values.yaml: |-
    replicaCount: 1

    ingress:
      enabled: true
      className: "nginx-internal"
      annotations:
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        kubernetes.io/ingress.class: nginx-internal
      hosts:
        - host: prowl.drik.it
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: prowlarr-certs
          hosts:
            - prowl.drik.it

    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 30Gi

    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        memory: 256Mi
