---
apiVersion: v1
kind: ConfigMap
metadata:
  name: signal-cli-values
  namespace: signal-cli
data:
  values.yaml: |-
    replicaCount: 1

    ingress:
      enabled: true
      className: "nginx-internal"
      annotations:
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        kubernetes.io/ingress.class: nginx-internal
      hosts:
        - host: signal.drik.it
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: signal-cli-certs
          hosts:
            - signal.drik.it

    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 30Gi

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 256Mi
