---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: sonarr
spec:
  chart:
    spec:
      chart: sonarr
      version: 0.1.*
      sourceRef:
        kind: HelmRepository
        name: drik-homelab
        namespace: flux-system
  interval: 30m
  timeout: 25m
  releaseName: sonarr
  valuesFrom:
  - kind: ConfigMap
    name: sonarr-values
    valuesKey: values.yaml
