---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarr-values
  namespace: sonarr
data:
  values.yaml: |-
    replicaCount: 1

    ingress:
      enabled: true
      className: "nginx-internal"
      annotations:
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        kubernetes.io/ingress.class: nginx-internal
      hosts:
        - host: son.drik.it
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: sonarr-certs
          hosts:
            - son.drik.it

    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 30Gi
      data:
        enabled: true
        storageClass: nfs-media
        accessMode: ReadWriteMany
        size: 41Ti

    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        memory: 512Mi
