---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: kubernetes-dashboard
spec:
  chart:
    spec:
      chart: oauth2-proxy
      version: 7.0.*
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
  interval: 30m
  timeout: 25m
  releaseName: oauth2-proxy
  valuesFrom:
  - kind: ConfigMap
    name: oauth2-proxy-values
    valuesKey: values.yaml
  - kind: Secret
    name: oauth2-proxy-secret-values
    valuesKey: notesPlain
