---
apiVersion: v1
kind: ConfigMap
metadata:
  name: subgen-values
  namespace: bazarr
data:
  values.yaml: |-
    replicaCount: 1
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 30Gi

    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        memory: 2Gi
