---

zfs_zpools:
  - name: zpool1
    devices:
      - /dev/vdb
      - /dev/vdc
      - /dev/vdd
    raid: raidz2
    datasets:
      - name: data
      - name: backup
        properties: >
          -o compression=zstd-9

zfs_default_zpool_compression: lz4
zfs_default_recordsize: 1M

zfs_lts_packages:
  - zfs-dkms
  - zfs-utils
zfs_git_packages:
  - zfs-dkms-git
  - zfs-utils-git
zfs_packages: "{{ zfs_lts_packages if installation_kernel_version == 'linux-lts' else zfs_git_packages }}"
