---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jellyseerr-values
  namespace: jellyseerr
data:
  values.yaml: |-
    replicaCount: 1
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        memory: 1Gi
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: jellys.drik.it
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: jellyseerr-certs
          hosts:
            - jellys.drik.it

    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 30Gi
